config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :staffs
  resources :schedules
  resources :planes do
    get :buy, on: :collection
    get :order, on: :collection
  end
  resources :xroutes
  resources :hubs
  resources :books
  resources :investments
  resources :running_costs
  resources :slots_allocations
  resources :territories

  resources :plane_models do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :countries do
    get :filter, on: :collection
  end

  resources :cities do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :plane_model_families do
    get :filter, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :hub, optional: true
  belongs_to :plane, optional: true
  belongs_to :user, optional: true

  def self.hire_officer(hub_id)
    @name = "#{StaffName.find(StaffName.pluck(:id).sample).name} #{StaffName.find(StaffName.pluck(:id).sample).surname}"
    @hub_id = hub_id
    Staff.new(name: @name, job: 'officer', hub_id: @hub_id, salary: 4000)
  end

  def self.hire_pilots(plane_id)
    @name = "#{StaffName.find(StaffName.pluck(:id).sample).name} #{StaffName.find(StaffName.pluck(:id).sample).surname}"
    @plane_id = plane_id
    Staff.new(name: @name, job: 'pilot', plane_id: @plane_id, salary: 12000)
  end

  def self.hire_attendant(plane_id)
    @name = "#{StaffName.find(StaffName.pluck(:id).sample).name} #{StaffName.find(StaffName.pluck(:id).sample).surname}"
    @plane_id = plane_id
    Staff.new(name: @name, job: 'attendant', plane_id: @plane_id, salary: 6000)
  end

  def hub_name
    if self.hub == nil
      return nil
    else
      return self.hub.name
    end
  end

  def plane_name
    if self.plane == nil
      return nil
    else
      return self.plane.name
    end
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:hub_id, :plane_id, :job, :salary, :name)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="control-group">
    <%= form.label :hub_id %>
    <div class="controls">
      <%= collection_select( :staff, :hub_id, Hub.all, :id, :name, { :include_blank => true }, { :multiple => false } ) %>
    </div>
  </div>

  <div class="control-group">
    <%= form.label :plane_id %>
    <div class="controls">
      <%= collection_select( :staff, :plane_id, Plane.all, :id, :name, { :include_blank => true }, { :multiple => false } ) %>
    </div>
  </div>

  <div class="field">
    <%= form.label :job %>
    <%= form.text_field :job %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hub</th>
      <th>Plane</th>
      <th>Job</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.hub_name %></td>
        <td><%= staff.plane_name %></td>
        <td><%= staff.job %></td>
        <td><%= staff.salary %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Hub:</strong>
  <%= @staff.hub_name %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @staff.plane_name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @staff.job %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @staff.salary %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>