config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :staffs
  resources :schedules
  resources :planes do
    get :buy, on: :collection
    get :order, on: :collection
  end
  resources :xroutes
  resources :hubs
  resources :books
  resources :investments
  resources :running_costs
  resources :slots_allocations
  resources :territories

  resources :plane_models do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :countries do
    get :filter, on: :collection
  end

  resources :cities do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :plane_model_families do
    get :filter, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :plane
  has_many :flight
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:plane_id, :xroute_id, :duration, :td1, :ta1, :td2, :ta2)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= form.label :plane_id %>
    <div class="controls">
      <%= collection_select( :schedule, :plane_id, Plane.all, :id, :name, {}, { multiple: false } ) %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :td1 %>
    <%= form.number_field :td1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Plane</th>
      <th>Xroute</th>
      <th>Duration</th>
      <th>Td1</th>
      <th>Ta1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.plane.name %></td>
        <td><%= schedule.xroute.name %></td>
        <td><%= schedule.duration %></td>
        <td><%= schedule.td1 %></td>
        <td><%= schedule.ta1 %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p>
  <strong>Plane:</strong>
  <%= @schedule.plane.name %>
</p>

<p>
  <strong>Xroute:</strong>
  <%= @schedule.xroute.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @schedule.duration %>
</p>

<p>
  <strong>Td1:</strong>
  <%= @schedule.td1 %>
</p>

<p>
  <strong>Ta1:</strong>
  <%= @schedule.ta1 %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>