config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :staffs
  resources :schedules
  resources :planes do
    get :buy, on: :collection
    get :order, on: :collection
  end
  resources :xroutes
  resources :hubs
  resources :books
  resources :investments
  resources :running_costs
  resources :slots_allocations
  resources :territories

  resources :plane_models do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :countries do
    get :filter, on: :collection
  end

  resources :cities do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :plane_model_families do
    get :filter, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plane_model.rb
class PlaneModel < ApplicationRecord
  belongs_to :plane_manufacturers, optional: true
  has_many :seat_configuration

  def counter
    @counter += 100
    self.update(counter: @counter)
    return @counter
  end
  
end

app/controllers/plane_models_controller.rb
class PlaneModelsController < ApplicationController
  before_action :set_plane_model, only: [:show, :edit, :update, :destroy]

  # GET /plane_models
  # GET /plane_models.json
  def index
    @plane_models = PlaneModel.all
    @list = PlaneModel.where(plane_model_family_id: params[:plane_model_family_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /plane_models/1
  # GET /plane_models/1.json
  def show
    @seat_configurations = SeatConfiguration.where(plane_model_id: params[:plane_model_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /plane_models/new
  def new
    @plane_model = PlaneModel.new
  end

  # GET /plane_models/1/edit
  def edit
  end

  # POST /plane_models
  # POST /plane_models.json
  def create
    @plane_model = PlaneModel.new(plane_model_params)

    respond_to do |format|
      if @plane_model.save
        format.html { redirect_to @plane_model, notice: 'Plane model was successfully created.' }
        format.json { render :show, status: :created, location: @plane_model }
      else
        format.html { render :new }
        format.json { render json: @plane_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plane_models/1
  # PATCH/PUT /plane_models/1.json
  def update
    respond_to do |format|
      if @plane_model.update(plane_model_params)
        format.html { redirect_to @plane_model, notice: 'Plane model was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane_model }
      else
        format.html { render :edit }
        format.json { render json: @plane_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plane_models/1
  # DELETE /plane_models/1.json
  def destroy
    @plane_model.destroy
    respond_to do |format|
      format.html { redirect_to plane_models_url, notice: 'Plane model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane_model
      @plane_model = PlaneModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_model_params
      params.require(:plane_model).permit(:name, :range, :avg_speed, :max_pas, :fuel_use, :cost, :maintanence, :pilots, :hosts)
    end
end

app/helpers/plane_models_helper.rb
module PlaneModelsHelper
end

app/views/plane_models/_detail.html.erb
<div class="details">
  <h1><%= @plane_model.name %></h1>
  <ol>
    Size: <%= if @plane_model.size == 1 then "Narrow Body" else "Wide Body" end  %><br>
    Range: <%= @plane_model.range %><br>
    Cruising Speed: <%= @plane_model.avg_speed %><br>
    Fuel Consumption: <%= "#{@plane_model.fuel_use} liters / km"  %><br>
    Maintanence Cost <%= "#{@plane_model.maintanence} / 3 months" %><br>
    Maximum Passenger (1 Class): <%= @plane_model.max_pas %><br>
  </ol>
  <h4>Staff Requirement</h4>
  <ol>
    Pilots: <%= @plane_model.pilots %><br>
    Flight Attendants: <%= @plane_model.hosts %><br>
  </ol>
  <h4>Listing Price : <%= @plane_model.cost %></h4>
  <table class="seat_configuration">
    <tr>
      <th>Seat Configurations</th>
      <th>Economy Class</th>
      <th>Business Class</th>
      <th>First Class</th>
      <th>Total Capacity</th>
    </tr>
    <% @seat_configurations.each do |sc| %>
    <tr>
      <td><%= "E#{sc.economy_class}/B#{sc.business_class}/F#{sc.first_class}"%></td>
      <td><%= sc.economy_class %></td>
      <td><%= sc.business_class %></td>
      <td><%= sc.first_class %></td>
      <td><%= sc.passenger %></td>
    </tr>
    <% end %>
  </table>
</div>
<p><%= link_to "Back to Plane Model Selection", filter_plane_models_path(plane_model_family_id: PlaneModelFamily.find(@plane_model.plane_model_family_id)), remote:true %></p>

app/views/plane_models/_index.html.erb
<h2>Plane Models</h2>
<ol class="plane_model">
  <% @list.each do |plane_model| %>
    <button type="button" id="select-pla_mod-button" data-remote="true" data-url="/plane_models/<%=plane_model.id%>" data-params="plane_model_id=<%=plane_model.id%>"><%=plane_model.name%></button>
  <% end %>
</ol>

app/views/plane_models/_show.html.erb
<div class="details">
  <h1><%= @plane_model.name %></h1>
  <ol>
    Size: <%= if @plane_model.size == 1 then "Narrow Body" else "Wide Body" end  %><br>
    Range: <%= @plane_model.range %><br>
    Cruising Speed: <%= @plane_model.avg_speed %><br>
    Fuel Consumption: <%= "#{@plane_model.fuel_use} liters / km"  %><br>
    Maintanence Cost <%= "#{@plane_model.maintanence} / 3 months" %><br>
    Maximum Passenger (1 Class): <%= @plane_model.max_pas %><br>
  </ol>
  <h4>Staff Requirement</h4>
  <ol>
    Pilots: <%= @plane_model.pilots %><br>
    Flight Attendants: <%= @plane_model.hosts %><br>
  </ol>
  <h4>Listing Price : <%= @plane_model.cost %></h4>
  <table class="seat_configuration">
    <tr>
      <th>Seat Configurations</th>
      <th>Economy Class</th>
      <th>Business Class</th>
      <th>First Class</th>
      <th>Total Capacity</th>
    </tr>
    <% @seat_configurations.each do |sc| %>
    <tr class="sc-rows">
      <td><%= "E#{sc.economy_class}/B#{sc.business_class}/F#{sc.first_class}"%></td>
      <td><%= sc.economy_class %></td>
      <td><%= sc.business_class %></td>
      <td><%= sc.first_class %></td>
      <td><%= sc.passenger %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/plane_models/index.html.erb
<section id= "pla_man-section">
  <%= render partial: 'plane_manufacturers/index' %>
</section>

<section id= "pla_mod_fam-section">
</section>

<section id= "pla_mod-section">
</section>

<section id= "pla_mod-detail-section">
</section>

<%= link_to 'Back to Home Page', root_path %>

app/views/plane_models/index.js.erb
$('.buy-buttons').empty()
$('.buy-controls').empty()
$('.buy-controls').css("display", "none")
$('.buy-inputs').empty()
$('.buy-inputs').css("display", "none")
$('#plane-count').val(1)
$('#errors-section').empty()
$('#pla_mod-detail-section').empty()
$('#pla_mod-section').empty()
$('#pla_mod-section').append("<%= j render partial: 'plane_models/index' %>");

app/views/plane_models/show.html.erb
<section id= "pla_man-section">
</section>

<section id= "pla_mod_fam-section">
</section>

<section id= "pla_mod-section">
</section>

<section id= "pla_mod_detail-section">
  <%= render 'show', plane_model: @plane_model %>
</section>

<%= link_to 'Back', plane_models_path %>

app/views/plane_models/show.js.erb
$('.buy-buttons').empty()
$('.buy-controls').empty()
$('.buy-controls').css("display", "none")
$('.buy-inputs').empty()
$('.buy-inputs').css("display", "none")
$('#plane-count').val(1)
$('#errors-section').empty()
$('#pla_mod-detail-section').empty()
$('#pla_mod-detail-section').append("<%= j render partial: 'plane_models/show' %>");
$('#pla_mod-detail-section').attr("plane_model_id", "<%= @plane_model.id %>")
if ($('meta[name=pjs]').attr('controller') == 'planes' && $('meta[name=pjs]').attr('action') == 'new'){
  var $plane_model_id = $('#pla_mod-detail-section').attr("plane_model_id")
  $.ajax({
    url: "/planes/new",
    data: { plane_model_id: $plane_model_id },
    global: false,
    dataType: "script",
  });
}