config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :staffs
  resources :schedules
  resources :planes do
    get :buy, on: :collection
    get :order, on: :collection
  end
  resources :xroutes
  resources :hubs
  resources :books
  resources :investments
  resources :running_costs
  resources :slots_allocations
  resources :territories

  resources :plane_models do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :countries do
    get :filter, on: :collection
  end

  resources :cities do
    get :filter, on: :collection
    get :detail, on: :collection
  end

  resources :plane_model_families do
    get :filter, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/xroute.rb
class Xroute < ApplicationRecord

  has_many :city
  has_many :user
  has_many :flight

  after_create :calculate, on: :create

  def origin
    City.find(self.origin)
  end

  def destination
    City.find(self.destination)
  end

  def calculate                                     #Returns distance between 2 cities
    @rad_per_deg = Math::PI/180                     # PI / 180
    @rkm = 6371                                     # Earth radius in kilometers
    @origin = self.origin
    @destination = self.destination
    @lat1_rad = @origin.latitude * @rad_per_deg
    @lon1_rad = @origin.longtitude * @rad_per_deg
    @lat2_rad = @destination.latitude * @rad_per_deg
    @lon2_rad = @destination.longtitude * @rad_per_deg
    @dlat_rad = @lat2_rad - @lat1_rad               # Delta, converted to rad
    @dlon_rad = @lon2_rad - @lon1_rad               # Delta, converted to rad

    a = Math.sin(@dlat_rad/2)**2 + Math.cos(@lat1_rad) * Math.cos(@lat2_rad) * Math.sin(@dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    @distance = @rkm * c                            # Delta in kilometers

    @max_num_pas = (@origin.population + @destination.population) / 240
    @fcd = @max_num_pas / 1000 * 3
    @bcd = @fcd * 10
    @ecd = @max_num_pas - @bdc - @fcd

    self.update(distance: @distance, max_num_pas: @max_num_pas, ecd: @ecd, bcd: @bcd, fcd: @fcd)
    return self.distance, self.max_num_pas
  end

  def name
    @origin = self.origin
    @destination = self.destination
    return "#{@origin.name}-#{@destination.name}"
  end
end

app/controllers/xroutes_controller.rb
class XroutesController < ApplicationController
  before_action :set_xroute, only: [:show, :edit, :update, :destroy]

  # GET /xroutes
  # GET /xroutes.json
  def index
    @xroutes = Xroute.all
  end

  # GET /xroutes/1
  # GET /xroutes/1.json
  def show
  end

  # GET /xroutes/new
  def new
    @xroute = Xroute.new
  end

  # GET /xroutes/1/edit
  def edit
  end

  # POST /xroutes
  # POST /xroutes.json
  def create
    @xroute = Xroute.new(xroute_params)

    respond_to do |format|
      if @xroute.save
        format.html { redirect_to @xroute, notice: 'Xroute was successfully created.' }
        format.json { render :show, status: :created, location: @xroute }
      else
        format.html { render :new }
        format.json { render json: @xroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xroutes/1
  # PATCH/PUT /xroutes/1.json
  def update
    respond_to do |format|
      if @xroute.update(xroute_params)
        format.html { redirect_to @xroute, notice: 'Xroute was successfully updated.' }
        format.json { render :show, status: :ok, location: @xroute }
      else
        format.html { render :edit }
        format.json { render json: @xroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xroutes/1
  # DELETE /xroutes/1.json
  def destroy
    @xroute.destroy
    respond_to do |format|
      format.html { redirect_to xroutes_url, notice: 'Xroute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xroute
      @xroute = Xroute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xroute_params
      params.require(:xroute).permit(:hub_id, :city_id, :distance, :max_num_pas, :operating_cost)
    end
end

app/helpers/xroutes_helper.rb
module XroutesHelper
end

app/views/xroutes/_form.html.erb
<%= form_with(model: xroute, local: true) do |form| %>
  <% if xroute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xroute.errors.count, "error") %> prohibited this xroute from being saved:</h2>

      <ul>
      <% xroute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= form.label :hub_id %>
    <div class="controls">
      <%= collection_select( :xroute, :hub_id, Hub.all, :id, :name, {}, { :multiple => false } ) %>
    </div>
  </div>

  <div class="control-group">
    <%= form.label :city_id %>
    <div class="controls">
      <%= collection_select( :xroute, :city_id, City.all, :id, :name, {}, { :multiple => false } ) %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/xroutes/edit.html.erb
<h1>Editing Xroute</h1>

<%= render 'form', xroute: @xroute %>

<%= link_to 'Show', @xroute %> |
<%= link_to 'Back', xroutes_path %>

app/views/xroutes/index.html.erb
<h1>Xroutes</h1>

<table>
  <thead>
    <tr>
      <th>Hub</th>
      <th>City</th>
      <th>Distance</th>
      <th>Max num pas</th>
      <th>Operating cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xroutes.each do |xroute| %>
      <tr>
        <td><%= xroute.hub.name %></td>
        <td><%= xroute.city.name %></td>
        <td><%= xroute.distance %></td>
        <td><%= xroute.max_num_pas %></td>
        <td><%= xroute.operating_cost %></td>
        <td><%= link_to 'Show', xroute %></td>
        <td><%= link_to 'Edit', edit_xroute_path(xroute) %></td>
        <td><%= link_to 'Destroy', xroute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xroute', new_xroute_path %>

app/views/xroutes/new.html.erb
<h1>New Xroute</h1>

<%= render 'form', xroute: @xroute %>

<%= link_to 'Back', xroutes_path %>

app/views/xroutes/show.html.erb
<p>
  <strong>Hub:</strong>
  <%= @xroute.hub.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @xroute.city.name %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @xroute.distance %>
</p>

<p>
  <strong>Max num pas:</strong>
  <%= @xroute.max_num_pas %>
</p>

<p>
  <strong>Operating cost:</strong>
  <%= @xroute.operating_cost %>
</p>

<%= link_to 'Edit', edit_xroute_path(@xroute) %> |
<%= link_to 'Back', xroutes_path %>